import { useEffect, useState } from 'react'
import { FolderKanban, Plus, Trash2 } from 'lucide-react'
import { api, errorMessage } from '../api'
import { EmptyState, Modal, PageHeader } from '../components'
import type { ResourceGroup, Service } from '../types'

export function ResourceGroupsPage() {
  const [groups, setGroups] = useState<ResourceGroup[]>([])
  const [services, setServices] = useState<Service[]>([])
  const [createOpen, setCreateOpen] = useState(false)
  const [assignGroup, setAssignGroup] = useState<ResourceGroup | null>(null)
  const [selectedServices, setSelectedServices] = useState<number[]>([])
  const [form, setForm] = useState({ name: '', description: '' })
  const [message, setMessage] = useState('')
  async function load() { const [groupItems, serviceItems] = await Promise.all([api.resourceGroups(), api.services()]); setGroups(groupItems); setServices(serviceItems) }
  useEffect(() => { load().catch((error) => setMessage(errorMessage(error))) }, [])
  async function create(event: React.FormEvent) { event.preventDefault(); try { await api.createResourceGroup(form); setCreateOpen(false); setForm({ name: '', description: '' }); await load() } catch (error) { setMessage(errorMessage(error)) } }
  function openAssign(group: ResourceGroup) { setSelectedServices(services.filter((service) => service.resource_group_id === group.id).map((service) => service.id)); setAssignGroup(group) }
  async function assign(event: React.FormEvent) { event.preventDefault(); if (!assignGroup) return; try { const moving = services.filter((service) => selectedServices.includes(service.id) && service.resource_group_id !== assignGroup.id); await Promise.all(moving.map((service) => api.updateService(service.id, { resource_group_id: assignGroup.id }))); setAssignGroup(null); await load(); setMessage('服务已移动到资源组') } catch (error) { setMessage(errorMessage(error)) } }
  async function remove(group: ResourceGroup) { if (!confirm(`确认删除资源组“${group.name}”？`)) return; try { await api.deleteResourceGroup(group.id); await load() } catch (error) { setMessage(errorMessage(error)) } }
  return <><PageHeader eyebrow="RESOURCE SCOPE" title="资源组" description="将服务归入唯一资源组，再以资源组为单位授权用户。" action={<button className="primary-button" onClick={() => setCreateOpen(true)}><Plus size={18} />新增资源组</button>} />{message && <div className="notice">{message}</div>}<section className="resource-grid">{groups.length === 0 ? <div className="data-card full-span"><EmptyState title="暂无资源组" description="创建资源组后再新增服务。" /></div> : groups.map((group) => <article className="resource-card" key={group.id}><header><div className="service-icon"><FolderKanban size={20} /></div><div><h2>{group.name}</h2><p>{group.description || '未填写说明'}</p></div></header><dl><div><dt>服务</dt><dd>{group.service_count}</dd></div><div><dt>用户</dt><dd>{group.user_count}</dd></div></dl><footer><button className="ghost-button" onClick={() => openAssign(group)}>分配服务</button><button className="danger-button" disabled={group.service_count > 0} onClick={() => remove(group)}><Trash2 size={16} /></button></footer></article>)}</section>{createOpen && <Modal title="新增资源组" onClose={() => setCreateOpen(false)}><form className="form-grid" onSubmit={create}><label>名称<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label className="wide-field">说明<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><div className="form-actions"><button type="button" className="secondary-button" onClick={() => setCreateOpen(false)}>取消</button><button className="primary-button">创建</button></div></form></Modal>}{assignGroup && <Modal title={`分配服务 · ${assignGroup.name}`} onClose={() => setAssignGroup(null)}><form onSubmit={assign}><div className="grant-list">{services.map((service) => <label key={service.id}><input type="checkbox" checked={selectedServices.includes(service.id)} disabled={service.resource_group_id === assignGroup.id} onChange={(event) => setSelectedServices(event.target.checked ? [...selectedServices, service.id] : selectedServices.filter((id) => id !== service.id))} /><span><strong>{service.name}</strong><small>{service.resource_group_name} · {service.host_name}</small></span></label>)}</div><div className="form-actions"><button type="button" className="secondary-button" onClick={() => setAssignGroup(null)}>取消</button><button className="primary-button">移动选中服务</button></div></form></Modal>}</>
}
